development:
  host: localhost
  database: ron_paul_development

test:
  host: localhost
  database: ron_paul_test

staging:
  host: staff.mongohq.com
  port: 10003
  username: seed_blocks
  password: 533dbl0ck5
  database: endorse_liberty_stg


# set these environment variables on your prod server
production:
  host: locke.mongohq.com
  port: 10000
  username: seed_blocks
  password: 533dbl0ck5
  database: endorse_liberty_prod
